### ISSUE TITLE
Vektor erzeugen und Sound abspielen

### ISSUE THREAD

**Issue by OccamsBeard** [friedz/sonic-pong#9]
+ Steigung,
+ Richtung,
+ Y-Achsenabschnitt 

sollen im Vektor enthalten sein. Wenn sich der Vektor ändert, soll der Tonerzeugung aktiv der neue Vektor weitergegeben werden (bzw. ein entsprechendes anderes Ereignis).

**ToDo**
- [ ] `playSound(currentVector)` soll `currentVector` an Scruby-Funktion weitergeben
- [ ] und entsprechender Sound soll erzeugt werden
- [x] Variable `currentVector` existiert in Klasse `Ball` und enthält Steigung, Y-Achsenabschnitt, Richtung
- [x] Methode `PlaySound` existiert in Klasse `Frame` (weil nur `frame` mit QML kommunizieren kann).
- [x] Methode `PlaySound` wird in QML-Datei über `frame` getriggert

Verwandt mit Issue #5

**Comment by OccamsBeard** [comment]
Das ist jetzt doch nicht über scruby geregelt, auch wenn der Branch derzeit noch so heißt. Deshalb wird dieses Issue geschlossen und ggf. ein neues eröffnet, das besser passt.
